import js from '@eslint/js';

export default [
  {
    files: ['src/**/*.js'],
    ignores: ['node_modules/**', 'tests/**', 'eslint.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        chrome: 'readonly',
        console: 'readonly',
        document: 'readonly',
        window: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        navigator: 'readonly',
        crypto: 'readonly',
        Math: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        Object: 'readonly',
        Array: 'readonly',
        fetch: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        JSON: 'readonly',
        String: 'readonly',
        Date: 'readonly',
        parseInt: 'readonly',
        TextDecoder: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        Event: 'readonly'
      }
    },
    rules: {
      ...js.configs.recommended.rules,
      // Relaxed rules for Chrome extension development
      'no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_|^(lexHost|getRespectGroups|setRespectGroups|AI_MODELS|DEFAULT_MODEL|EXPIRY_PRESETS|DEFAULT_EXPIRY|VALID_TAB_GROUP_COLORS|encodeKey|decodeKey|isKeyExpired|saveAiConfig|loadAiConfig|stripQueryParams|buildAiPrompt|callOpenRouter|parseAiResponse|handleAiGroupTabs|handleApplyAiProposal|aiOrganize|COLOR_MAP|clumperResetStateForTest|clumperGetStateForTest|napFormatClock|napDayInfo|napNextWakeSummary|napRowTitle|napRowUrl|napGroupBadge|napGroupByDay)$',
        caughtErrorsIgnorePattern: '^_' // Ignore unused error parameters prefixed with _
      }],
      'no-console': 'off', // Console is used for debugging in extensions
      'no-undef': 'error',
      'semi': ['error', 'always'],
      'quotes': ['warn', 'single', { allowTemplateLiterals: true }]
    }
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        // Vitest globals
        describe: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        vi: 'readonly',
        global: 'writable',

        // Chrome extension globals
        chrome: 'readonly',
        console: 'readonly',
        document: 'readonly',
        window: 'readonly',
        URL: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        structuredClone: 'readonly',
        Map: 'readonly',
        Promise: 'readonly',
        Object: 'readonly',
        Array: 'readonly',
        Set: 'readonly',

        // Test helpers (defined by setup.js)
        dispatch: 'readonly',

        // DOM globals (jsdom-provided at test time)
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        setImmediate: 'readonly',
        navigator: 'readonly',

        // Node.js globals for test setup
        eval: 'readonly',
        
        DOMException: 'readonly',

        // Extension functions (loaded by setup.js)
        AI_KEY_ALARM: 'readonly',
        AI_PROTOCOL: 'readonly',
        MODELS_CACHE_VERSION: 'readonly',
        aiKeyState: 'readonly',
        maxTokensForTabs: 'readonly',
        modelInfo: 'readonly',
        resolveDefaultModel: 'readonly',
        mapOpenRouterHttpError: 'readonly',
        DEFAULT_MODEL: 'readonly',
        lexHost: 'readonly',
        getTabGroupsInfo: 'readonly',
        getTabsWithGroupInfo: 'readonly',
        findDuplicateTabs: 'readonly',
        sortWindowTabs: 'readonly',
        sortTabsAsUnits: 'readonly',
        tabSplitViewId: 'readonly',
        splitWriteSupported: 'readonly',
        planCompactPairs: 'readonly',
        captureSplitPairs: 'readonly',
        restoreSplitPairs: 'readonly',
        handleCompactWindow: 'readonly',
        handleExpandWindow: 'readonly',
        analyzeDomainDistribution: 'readonly',
        getRespectGroups: 'readonly',
        setRespectGroups: 'readonly',
        saveUserPreference: 'readonly',
        loadUserPreferences: 'readonly',
        initModeToggle: 'readonly',
        handleSortCurrentWindow: 'readonly',
        sortAllWindows: 'readonly',
        sortCurrentWindow: 'readonly',
        handleSortCurrentWindow: 'readonly',
        handleRemoveDuplicatesWindow: 'readonly',
        handleExtractDomain: 'readonly',
        handleExtractAllDomains: 'readonly',
        handleExtractAllDomainsConfirmation: 'readonly',
        splitConfirmWaiters: 'readonly',
        handleMoveAllToSingleWindow: 'readonly',
        moveTabsWithGroups: 'readonly',
        initModeToggle: 'readonly',
        extractDomain: 'readonly',
        removeDuplicatesWindow: 'readonly',
        removeDuplicatesAllWindows: 'readonly',
        removeDuplicatesGlobally: 'readonly',
        extractAllDomains: 'readonly',
        moveAllToSingleWindow: 'readonly',
        copyTabsToClipboard: 'readonly',
        copyFeedbackMessage: 'readonly',
        copyThisWindow: 'readonly',
        copyAllWindows: 'readonly',
        flattenWindow: 'readonly',
        compactWindow: 'readonly',
        expandWindow: 'readonly',
        updateStatusBar: 'readonly',
        loadBrowserSnapshot: 'readonly',
        describeActionResult: 'readonly',
        showActionResult: 'readonly',
        actionResultKind: 'readonly',
        updateToastSpace: 'readonly',
        sendAction: 'readonly',
        submitSnooze: 'readonly',
        openSnoozePicker: 'readonly',
        closeSnoozePicker: 'readonly',
        formatTabsAsText: 'readonly',
        handleCopyTabs: 'readonly',
        updateContent: 'readonly',
        setupEventListeners: 'readonly',
        respond: 'readonly',
        encodeKey: 'readonly',
        decodeKey: 'readonly',
        saveAiConfig: 'readonly',
        loadAiConfig: 'readonly',
        isKeyExpired: 'readonly',
        buildAiPrompt: 'readonly',
        parseAiResponse: 'readonly',
        stripQueryParams: 'readonly',
        AI_MODELS: 'readonly',
        VALID_TAB_GROUP_COLORS: 'readonly',
        formatModelCost: 'readonly',
        normalizeOpenRouterModel: 'readonly',
        mergeModelsForPicker: 'readonly',
        curatedModelsAsPickerEntries: 'readonly',
        getOpenRouterModels: 'readonly',
        fetchOpenRouterModels: 'readonly',
        buildTabGroupsJsonSchema: 'readonly',
        buildOpenRouterRequestBody: 'readonly',
        MODELS_CACHE_KEY: 'readonly',
        MODELS_CACHE_TTL_MS: 'readonly',
        aiOrganize: 'readonly',
        popupSetupEventListeners: 'readonly',

        // Tab snoozing functions (loaded by setup.js)
        computePresetWakeTime: 'readonly',
        nextWeekdayAt: 'readonly',
        clampWakeAt: 'readonly',
        isSnoozeableUrl: 'readonly',
        buildSnoozeSummary: 'readonly',
        createSnoozeRecord: 'readonly',
        snoozeTabs: 'readonly',
        handleSnoozeTab: 'readonly',
        handleSnoozeSelected: 'readonly',
        handleSnoozeWindow: 'readonly',
        handleSnoozeGroup: 'readonly',
        handleListSnoozed: 'readonly',
        handleWakeNow: 'readonly',
        handleCancelSnooze: 'readonly',
        handleRestoreSnoozed: 'readonly',
        handleSnoozeAlarm: 'readonly',
        wakeSnoozedRecord: 'readonly',
        restoreSnoozedRecord: 'readonly',
        reconcileSnoozeAlarms: 'readonly',
        SNOOZE_PRESETS: 'readonly',
        formatWakeTime: 'readonly',
        renderSnoozedList: 'readonly',
        updateSnoozeButtonState: 'readonly',
        updateSplitViewButtons: 'readonly',
        initSnoozeUi: 'readonly',
        snoozePresetLabel: 'readonly',
        wakeNow: 'readonly',
        discardSnooze: 'readonly',
        showDiscardNotice: 'readonly',
        undoDiscard: 'readonly',

        // Keyboard shortcut functions (loaded by setup.js)
        buildHotkeyMap: 'readonly',
        refreshHotkeys: 'readonly',
        handleHotkeyKeydown: 'readonly',
        isTextInputTarget: 'readonly',
        isHotkeyVisible: 'readonly',

        // Nap room functions (loaded by setup.js)
        napFormatClock: 'readonly',
        napDayInfo: 'readonly',
        napNextWakeSummary: 'readonly',
        napRowTitle: 'readonly',
        napRowUrl: 'readonly',
        napGroupBadge: 'readonly',
        napGroupByDay: 'readonly',
        napRenderAll: 'readonly',
        napScheduleMidnightRefresh: 'readonly',
        napWakeNow: 'readonly',
        napWakeAll: 'readonly',
        napDiscard: 'readonly',
        napShowDiscardNotice: 'readonly',
        napUndoDiscard: 'readonly',

        // ai-proposal.js / callOpenRouter / handleAiGroupTabs exposures (loaded by setup.js)
        escapeHtml: 'readonly',
        moveTab: 'readonly',
        renderGroup: 'readonly',
        setupActionButtons: 'readonly',
        callOpenRouter: 'readonly',
        handleAiGroupTabs: 'readonly',
        handleApplyAiProposal: 'readonly',
        saveAiDefaultModel: 'readonly',
        deleteAiKey: 'readonly',

        // ai-config.js (shared AI script, loaded by setup.js)
        HuddleAi: 'readonly'
      }
    },
    rules: {
      ...js.configs.recommended.rules,
      'no-unused-vars': 'off', // Tests often have variables for demonstration
      'no-undef': 'error',
      'no-console': 'off'
    }
  }
];