"""Drift detection: compare a project's generated files against the lock and the bundled templates."""

import difflib
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from . import __version__
from .detect import detect_languages
from .generate import render_all
from .lock import LOCK_FILENAME, LockFile, hash_bytes, read_lock


class UnmanagedProjectError(Exception):
    """The directory has no .jdf-hooks.lock, so there is nothing to compare against."""


class FileState(StrEnum):
    UP_TO_DATE = "up-to-date"
    UPDATE_AVAILABLE = "update-available"
    MODIFIED = "modified"
    MISSING = "missing"
    OBSOLETE = "obsolete"  # in the lock but no longer generated for this language set


@dataclass(frozen=True)
class FileReport:
    path: str
    state: FileState
    stale: bool  # the bundled template differs from what the lock recorded
    new: bool = False  # rendered now but not present in the lock


@dataclass(frozen=True)
class CheckReport:
    lock: LockFile
    tool_version: str
    files: list[FileReport]

    @property
    def has_drift(self) -> bool:
        return any(f.state is not FileState.UP_TO_DATE for f in self.files)

    @property
    def version_changed(self) -> bool:
        return self.lock.jdf_hooks != self.tool_version


def check_project(
    target_dir: Path,
    templates_dir: Path | None = None,
    *,
    languages: set[str] | None = None,
    github_workflow: bool | None = None,
) -> CheckReport:
    """Compare every locked file against disk and against a fresh render.

    Args:
        target_dir: Project directory containing the lock file.
        templates_dir: Optional templates directory (bundled templates if omitted).
        languages: Override the lock's language set (used by `update --add/--remove`).
        github_workflow: Override the lock's github_workflow option.

    Raises:
        UnmanagedProjectError: if there is no lock file in target_dir.
        LockError: if the lock file cannot be parsed.
    """
    lock = read_lock(target_dir)
    if lock is None:
        raise UnmanagedProjectError(
            f"No {LOCK_FILENAME} in {target_dir} — generated by jdf-hooks < 1.2.0 or not by jdf-hooks. "
            "Run `jdf-hooks adopt` to record the existing files, or `jdf-hooks setup` to regenerate."
        )

    fresh = render_all(
        languages if languages is not None else set(lock.languages),
        lock.manager,
        templates_dir,
        github_workflow=lock.options.get("github_workflow", False) if github_workflow is None else github_workflow,
    )
    reports: list[FileReport] = []

    for rel_path in sorted(set(lock.files) | set(fresh)):
        locked_hash = lock.files.get(rel_path)
        fresh_hash = hash_bytes(fresh[rel_path]) if rel_path in fresh else None
        on_disk = target_dir / rel_path
        disk_hash = hash_bytes(on_disk.read_bytes()) if on_disk.is_file() else None

        if locked_hash is None:
            # The templates now produce a file this project never received.
            reports.append(FileReport(rel_path, FileState.UPDATE_AVAILABLE, stale=True, new=True))
            continue

        stale = fresh_hash != locked_hash
        if fresh_hash is None:
            state = FileState.OBSOLETE
        elif disk_hash is None:
            state = FileState.MISSING
        elif disk_hash != locked_hash:
            state = FileState.MODIFIED
        elif stale:
            state = FileState.UPDATE_AVAILABLE
        else:
            state = FileState.UP_TO_DATE
        reports.append(FileReport(rel_path, state, stale=stale))

    return CheckReport(lock=lock, tool_version=__version__, files=reports)


def undetected_languages(target_dir: Path, languages: list[str]) -> dict[str, list[str]]:
    """Languages detected in the project that are not in the given hook set, with detection reasons."""
    detected = detect_languages(target_dir)
    return {lang: reasons for lang, reasons in detected.items() if lang not in languages}


def diff_file(target_dir: Path, rel_path: str, templates_dir: Path | None = None, lock: LockFile | None = None) -> str:
    """Unified diff from the file on disk to a fresh render. Empty for binary or identical content."""
    if lock is None:
        lock = read_lock(target_dir)
        if lock is None:
            raise UnmanagedProjectError(f"No {LOCK_FILENAME} in {target_dir}")

    fresh_bytes = render_all(
        set(lock.languages),
        lock.manager,
        templates_dir,
        github_workflow=lock.options.get("github_workflow", False),
    ).get(rel_path, b"")
    on_disk = target_dir / rel_path
    disk_bytes = on_disk.read_bytes() if on_disk.is_file() else b""
    try:
        current = disk_bytes.decode()
        fresh = fresh_bytes.decode()
    except UnicodeDecodeError:
        return ""

    return "".join(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            fresh.splitlines(keepends=True),
            fromfile=f"{rel_path} (current)",
            tofile=f"{rel_path} (jdf-hooks {__version__})",
        )
    )
