"""Config file generation from per-language fragment files."""

import shutil
from pathlib import Path

# Mapping from language names to fragment file basenames
LANGUAGE_FRAGMENTS: dict[str, list[str]] = {
    "python": ["python", "python_typechecking"],
    "javascript": ["javascript"],
    "rust": ["rust"],
    "java": ["java"],
    "markdown": ["markdown"],
    "yaml": ["yaml"],
    "toml": ["toml"],
    "sql": ["sql"],
    "shell": ["shell"],
    "general": ["general"],
}

# Config files needed for each language
LANGUAGE_CONFIGS: dict[str, list[str]] = {
    "markdown": ["configs/markdown/markdownlint.json"],
    "yaml": ["configs/yaml/yamlfix.toml"],
    "toml": ["configs/toml/taplo.toml"],
    "sql": ["configs/sql/.sqlfluff"],
}


def get_templates_dir() -> Path:
    """Return the path to the bundled templates directory."""
    return Path(__file__).parent / "templates"


def load_fragments(
    manager: str,
    languages: set[str],
    templates_dir: Path,
) -> str:
    """Load and concatenate fragment files for selected languages.

    Args:
        manager: Either "precommit" or "lefthook".
        languages: Set of language names to include.
        templates_dir: Path to the templates directory.

    Returns:
        Concatenated fragment content.
    """
    fragments_dir = templates_dir / manager
    parts: list[str] = []

    # Iterate in dict insertion order for deterministic output
    for lang, fragment_names in LANGUAGE_FRAGMENTS.items():
        if lang not in languages:
            continue
        for name in fragment_names:
            fragment_path = fragments_dir / f"{name}.yml"
            if fragment_path.exists():
                parts.append(fragment_path.read_text())

    return "".join(parts)


def generate_precommit_config(
    target_dir: Path,
    languages: set[str],
    templates_dir: Path | None = None,
) -> Path:
    """Generate .pre-commit-config.yaml for the target project.

    Args:
        target_dir: Directory to write the config file to.
        languages: Set of languages to include hooks for.
        templates_dir: Optional templates directory (auto-detected if not provided).

    Returns:
        Path to the generated config file.
    """
    if templates_dir is None:
        templates_dir = get_templates_dir()

    header = """# ============================================================================
# PRE-COMMIT HOOKS CONFIGURATION
# ============================================================================
# Generated by jdf-hooks (https://github.com/joaodinissf/jdf-suite)
#
# Run: pre-commit install
# Test: pre-commit run --all-files
# ============================================================================
repos:
"""

    fragments = load_fragments("precommit", languages, templates_dir)
    output = header + fragments

    target_path = target_dir / ".pre-commit-config.yaml"
    target_path.write_text(output)

    return target_path


def generate_lefthook_config(
    target_dir: Path,
    languages: set[str],
    templates_dir: Path | None = None,
) -> Path:
    """Generate lefthook.yml for the target project.

    Args:
        target_dir: Directory to write the config file to.
        languages: Set of languages to include hooks for.
        templates_dir: Optional templates directory (auto-detected if not provided).

    Returns:
        Path to the generated config file.
    """
    if templates_dir is None:
        templates_dir = get_templates_dir()

    header = """# ============================================================================
# LEFTHOOK CONFIGURATION
# ============================================================================
# Generated by jdf-hooks (https://github.com/joaodinissf/jdf-suite)
#
# Run: lefthook install
# Test: lefthook run pre-commit --all-files
# ============================================================================
pre-commit:
  jobs:
"""

    fragments = load_fragments("lefthook", languages, templates_dir)
    output = header + fragments

    target_path = target_dir / "lefthook.yml"
    target_path.write_text(output)

    return target_path


def copy_config_files(
    target_dir: Path,
    languages: set[str],
    templates_dir: Path | None = None,
) -> list[Path]:
    """Copy necessary config files for selected languages.

    Args:
        target_dir: Directory to copy config files to.
        languages: Set of languages that need config files.
        templates_dir: Optional templates directory (auto-detected if not provided).

    Returns:
        List of paths to copied config files.
    """
    if templates_dir is None:
        templates_dir = get_templates_dir()

    copied_files: list[Path] = []

    for lang in languages:
        for config_path in LANGUAGE_CONFIGS.get(lang, []):
            source = templates_dir / config_path
            if source.exists():
                target = target_dir / config_path
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, target)
                copied_files.append(target)

    return copied_files


def generate_configs(
    target_dir: Path,
    languages: set[str],
    hook_manager: str,
    templates_dir: Path | None = None,
) -> dict[str, list[Path]]:
    """Generate all necessary config files for the target project.

    Args:
        target_dir: Directory to write config files to.
        languages: Set of languages to include.
        hook_manager: One of "lefthook", "pre-commit", or "both".
        templates_dir: Optional templates directory (auto-detected if not provided).

    Returns:
        Dictionary with "configs" and "hook_files" keys listing created files.
    """
    if templates_dir is None:
        templates_dir = get_templates_dir()

    result: dict[str, list[Path]] = {"hook_files": [], "configs": []}

    if hook_manager in ("lefthook", "both"):
        path = generate_lefthook_config(target_dir, languages, templates_dir)
        result["hook_files"].append(path)

    if hook_manager in ("pre-commit", "both"):
        path = generate_precommit_config(target_dir, languages, templates_dir)
        result["hook_files"].append(path)

    result["configs"] = copy_config_files(target_dir, languages, templates_dir)

    return result
