"""Config file generation from per-language fragment files."""

from pathlib import Path

from . import __version__
from .lock import LockFile, hash_bytes, write_lock

PRECOMMIT_FILENAME = ".pre-commit-config.yaml"
LEFTHOOK_FILENAME = "lefthook.yml"

# Mapping from language names to fragment file basenames
LANGUAGE_FRAGMENTS: dict[str, list[str]] = {
    "python": ["python", "python_typechecking"],
    "javascript": ["javascript"],
    "rust": ["rust"],
    "java": ["java"],
    "markdown": ["markdown"],
    "yaml": ["yaml"],
    "toml": ["toml"],
    "sql": ["sql"],
    "shell": ["shell"],
    "general": ["general"],
}

# Config files needed for each language
LANGUAGE_CONFIGS: dict[str, list[str]] = {
    "markdown": ["configs/markdown/markdownlint.json"],
    "yaml": ["configs/yaml/yamlfix.toml"],
    "toml": ["configs/toml/taplo.toml"],
    "sql": ["configs/sql/.sqlfluff"],
}


def get_templates_dir() -> Path:
    """Return the path to the bundled templates directory."""
    return Path(__file__).parent / "templates"


def load_fragments(
    manager: str,
    languages: set[str],
    templates_dir: Path,
) -> str:
    """Load and concatenate fragment files for selected languages.

    Args:
        manager: Either "precommit" or "lefthook".
        languages: Set of language names to include.
        templates_dir: Path to the templates directory.

    Returns:
        Concatenated fragment content.
    """
    fragments_dir = templates_dir / manager
    parts: list[str] = []

    # Iterate in dict insertion order for deterministic output
    for lang, fragment_names in LANGUAGE_FRAGMENTS.items():
        if lang not in languages:
            continue
        for name in fragment_names:
            fragment_path = fragments_dir / f"{name}.yml"
            if fragment_path.exists():
                parts.append(fragment_path.read_text())

    return "".join(parts)


def render_precommit(languages: set[str], templates_dir: Path | None = None) -> str:
    """Render the content of .pre-commit-config.yaml without writing it."""
    if templates_dir is None:
        templates_dir = get_templates_dir()

    header = """# ============================================================================
# PRE-COMMIT HOOKS CONFIGURATION
# ============================================================================
# Generated by jdf-hooks (https://github.com/joaodinissf/jdf-suite)
#
# Run: pre-commit install
# Test: pre-commit run --all-files
# ============================================================================
repos:
"""

    return header + load_fragments("precommit", languages, templates_dir)


def generate_precommit_config(
    target_dir: Path,
    languages: set[str],
    templates_dir: Path | None = None,
) -> Path:
    """Generate .pre-commit-config.yaml for the target project.

    Args:
        target_dir: Directory to write the config file to.
        languages: Set of languages to include hooks for.
        templates_dir: Optional templates directory (auto-detected if not provided).

    Returns:
        Path to the generated config file.
    """
    target_path = target_dir / PRECOMMIT_FILENAME
    target_path.write_text(render_precommit(languages, templates_dir))
    return target_path


def render_lefthook(languages: set[str], templates_dir: Path | None = None) -> str:
    """Render the content of lefthook.yml without writing it."""
    if templates_dir is None:
        templates_dir = get_templates_dir()

    header = """# ============================================================================
# LEFTHOOK CONFIGURATION
# ============================================================================
# Generated by jdf-hooks (https://github.com/joaodinissf/jdf-suite)
#
# Run: lefthook install
# Test: lefthook run pre-commit --all-files
# ============================================================================
pre-commit:
  jobs:
"""

    return header + load_fragments("lefthook", languages, templates_dir)


def generate_lefthook_config(
    target_dir: Path,
    languages: set[str],
    templates_dir: Path | None = None,
) -> Path:
    """Generate lefthook.yml for the target project.

    Args:
        target_dir: Directory to write the config file to.
        languages: Set of languages to include hooks for.
        templates_dir: Optional templates directory (auto-detected if not provided).

    Returns:
        Path to the generated config file.
    """
    target_path = target_dir / LEFTHOOK_FILENAME
    target_path.write_text(render_lefthook(languages, templates_dir))
    return target_path


def render_config_files(languages: set[str], templates_dir: Path | None = None) -> dict[str, bytes]:
    """Return the tool config files needed for the selected languages, keyed by relative path."""
    if templates_dir is None:
        templates_dir = get_templates_dir()

    rendered: dict[str, bytes] = {}
    for lang in sorted(languages):
        for config_path in LANGUAGE_CONFIGS.get(lang, []):
            source = templates_dir / config_path
            if source.exists():
                rendered[config_path] = source.read_bytes()
    return rendered


def render_all(
    languages: set[str],
    hook_manager: str,
    templates_dir: Path | None = None,
) -> dict[str, bytes]:
    """Render every file jdf-hooks would generate, keyed by path relative to the project.

    This is the single source of truth shared by generation and drift checking.
    """
    rendered: dict[str, bytes] = {}
    if hook_manager in ("lefthook", "both"):
        rendered[LEFTHOOK_FILENAME] = render_lefthook(languages, templates_dir).encode()
    if hook_manager in ("pre-commit", "both"):
        rendered[PRECOMMIT_FILENAME] = render_precommit(languages, templates_dir).encode()
    rendered.update(render_config_files(languages, templates_dir))
    return rendered


def copy_config_files(
    target_dir: Path,
    languages: set[str],
    templates_dir: Path | None = None,
) -> list[Path]:
    """Copy necessary config files for selected languages.

    Args:
        target_dir: Directory to copy config files to.
        languages: Set of languages that need config files.
        templates_dir: Optional templates directory (auto-detected if not provided).

    Returns:
        List of paths to copied config files.
    """
    copied_files: list[Path] = []
    for config_path, content in render_config_files(languages, templates_dir).items():
        target = target_dir / config_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
        copied_files.append(target)
    return copied_files


def generate_configs(
    target_dir: Path,
    languages: set[str],
    hook_manager: str,
    templates_dir: Path | None = None,
) -> dict[str, list[Path]]:
    """Generate all necessary config files for the target project.

    Args:
        target_dir: Directory to write config files to.
        languages: Set of languages to include.
        hook_manager: One of "lefthook", "pre-commit", or "both".
        templates_dir: Optional templates directory (auto-detected if not provided).

    Returns:
        Dictionary with "hook_files", "configs" and "lock" keys listing created files.
    """
    result: dict[str, list[Path]] = {"hook_files": [], "configs": [], "lock": []}

    rendered = render_all(languages, hook_manager, templates_dir)
    for rel_path, content in rendered.items():
        target = target_dir / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
        key = "hook_files" if rel_path in (LEFTHOOK_FILENAME, PRECOMMIT_FILENAME) else "configs"
        result[key].append(target)

    lock = LockFile(
        jdf_hooks=__version__,
        manager=hook_manager,
        languages=sorted(languages),
        files={rel_path: hash_bytes(content) for rel_path, content in rendered.items()},
    )
    result["lock"].append(write_lock(target_dir, lock))

    return result
