"""The .jdf-hooks.lock file: provenance for files generated by jdf-hooks.

Modelled on skills-lock.json from `npx skills`: generated files are owned by
jdf-hooks, the lock records what was generated and from which version, and
updates overwrite rather than merge.
"""

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

LOCK_FILENAME = ".jdf-hooks.lock"


class LockError(ValueError):
    """The lock file exists but cannot be parsed."""


def hash_bytes(data: bytes) -> str:
    """Return the content hash used in the lock file."""
    return f"sha256:{hashlib.sha256(data).hexdigest()}"


@dataclass(frozen=True)
class LockFile:
    """Contents of a .jdf-hooks.lock file."""

    jdf_hooks: str
    manager: str
    languages: list[str]
    files: dict[str, str]  # relative POSIX path -> content hash

    def to_json(self) -> str:
        data = {
            "jdf_hooks": self.jdf_hooks,
            "manager": self.manager,
            "languages": sorted(self.languages),
            "files": dict(sorted(self.files.items())),
        }
        return json.dumps(data, indent=2) + "\n"

    @classmethod
    def from_json(cls, text: str) -> "LockFile":
        try:
            data = json.loads(text)
            return cls(
                jdf_hooks=str(data["jdf_hooks"]),
                manager=str(data["manager"]),
                languages=sorted(str(lang) for lang in data["languages"]),
                files={str(k): str(v) for k, v in data["files"].items()},
            )
        except (json.JSONDecodeError, KeyError, TypeError, AttributeError) as e:
            raise LockError(f"Invalid {LOCK_FILENAME}: {e}") from e


def read_lock(target_dir: Path) -> LockFile | None:
    """Read the lock file from a project directory, or None if absent."""
    path = target_dir / LOCK_FILENAME
    if not path.exists():
        return None
    return LockFile.from_json(path.read_text())


def write_lock(target_dir: Path, lock: LockFile) -> Path:
    """Write the lock file into a project directory."""
    path = target_dir / LOCK_FILENAME
    path.write_text(lock.to_json())
    return path
